In [1]:
import numpy as np

## 1. Datatypes & Attributes

In [3]:
# Numpy main dataty is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5.0, 6.5]])

a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,20,30],
                [11,12,13],
                [21,22,23]]])
               

In [7]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 20, 30],
        [11, 12, 13],
        [21, 22, 23]]])

In [10]:
a1.shape

(3,)

In [11]:
a2.shape

(2, 3)

In [12]:
a3.shape

(2, 3, 3)

In [13]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [14]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [15]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [16]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [17]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [22]:
# Create a Data Frame from a numpy array
import pandas as pd
df = pd.DataFrame(a2)

In [23]:
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating Arrays

In [24]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [25]:
sample_array.dtype

dtype('int64')

In [27]:
ones = np.ones((3, 4), np.int8)
ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [28]:
type(ones)

numpy.ndarray

In [29]:
ones.dtype

dtype('int8')

In [33]:
zeroes = np.zeros((3, 4))
zeroes

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [36]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[1, 9, 3, 1, 7],
       [3, 9, 9, 2, 4],
       [0, 0, 1, 0, 2]])

In [37]:
random_array.shape

(3, 5)

In [39]:
random_array2 = np.random.random((5, 3))
random_array2

array([[0.50992338, 0.40142051, 0.77378737],
       [0.78919009, 0.51567223, 0.73003605],
       [0.90089642, 0.06940997, 0.90217437],
       [0.74447259, 0.67313703, 0.43358687],
       [0.99279574, 0.9471661 , 0.75363514]])

In [41]:
random_array3 = np.random.rand(5,3)
random_array3

array([[0.33833111, 0.35670903, 0.20124202],
       [0.98130186, 0.36224772, 0.66673255],
       [0.25415961, 0.69396414, 0.41753207],
       [0.89806962, 0.00357723, 0.18345286],
       [0.5146176 , 0.57549343, 0.32218865]])

## 3. Viewing Markdowns and Matrices

In [42]:
test = [0,1,2,3,4,5]
test[:]

[0, 1, 2, 3, 4, 5]

## 4. Manipulating and Comparing Arrays 

### Arithmetics

In [43]:
a1

array([1, 2, 3])

In [46]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [47]:
a1 + ones

array([2., 3., 4.])

In [48]:
a1 - ones

array([0., 1., 2.])

In [49]:
a1 * ones

array([1., 2., 3.])

In [50]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [51]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [53]:
massive_array = np.random.random(100000)
massive_array[:50]

array([0.62078862, 0.26152831, 0.12535414, 0.4011659 , 0.25529172,
       0.06250061, 0.39423051, 0.59564996, 0.28634905, 0.80261881,
       0.56030951, 0.67766451, 0.20545739, 0.65281548, 0.07506672,
       0.13050109, 0.45835815, 0.951561  , 0.59795431, 0.32032093,
       0.05064366, 0.58111951, 0.34567456, 0.14428074, 0.75985977,
       0.00526871, 0.59268986, 0.14608041, 0.39494882, 0.92565478,
       0.53608295, 0.29707275, 0.90185224, 0.32520553, 0.82822514,
       0.54908367, 0.06447534, 0.73161781, 0.93903835, 0.78539755,
       0.62606774, 0.21086769, 0.58871087, 0.74240439, 0.83576065,
       0.09395859, 0.034368  , 0.32334914, 0.47378482, 0.70910305])