# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [9]:
# Create a 1-dimensional NumPy array using np.array()
d1a = np.array([3,4,5])
d1a
# Create a 2-dimensional NumPy array using np.array()
d2a = np.array([[2,3,4],
                [4,5,6]])
d2a

# Create a 3-dimensional Numpy array using np.array()
d3a = np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]],
                [[1,2,3],
                 [4,5,6],
                 [7,8,9]]])
d3a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [13]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
d1a.shape, d1a.ndim, d1a.dtype, d1a.size, type(d1a)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [14]:
# Attributes of 2-dimensional array
d2a.shape, d2a.ndim, d2a.dtype, d2a.size, type(d2a)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [15]:
# Attributes of 3-dimensional array
d3a.shape, d3a.ndim, d3a.dtype, d3a.size, type(d3a)

((2, 3, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [20]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(d2a,
                 columns=["Mon", "Tue", "Wed"])
df

Mon  Tue  Wed
0    2    3    4
1    4    5    6

In [22]:
# Create an array of shape (10, 2) with only ones
ones = np.ones(shape=(10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [25]:
# Create an array of shape (7, 2, 3) of only zeros
zeroes = np.zeros(shape=(7,2,3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [28]:
# Create an array within a range of 0 and 100 with step 3
ints = np.arange(0, 100, 3)
ints

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [29]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
rand_a = np.random.randint(0,10, size=(7,2))
rand_a

array([[0, 4],
       [2, 4],
       [2, 2],
       [8, 0],
       [3, 3],
       [2, 9],
       [1, 4]])

In [30]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
rand_floats = np.random.random((3, 5))
rand_floats

array([[0.94939926, 0.24206257, 0.05377114, 0.21731166, 0.91542322],
       [0.69120986, 0.30990232, 0.19871199, 0.18982548, 0.79345992],
       [0.96363439, 0.403591  , 0.09953721, 0.47792665, 0.89456259]])

In [33]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_ints = np.random.randint(0, 10, size=(4, 6))
random_ints


array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?
- The numbers were the same

Are the numbers in the array different or the same? Why do think this is?
- Because the random seed is fixed

In [36]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
arr_random = np.random.randint(1, 10, size=(3,7))
arr_random


array([[2, 5, 8, 9, 9, 1, 9],
       [7, 9, 8, 1, 8, 8, 3],
       [1, 8, 3, 3, 1, 5, 7]])

In [37]:
# Find the unique numbers in the array you just created
unique_arr_random = np.unique(arr_random)
unique_arr_random

array([1, 2, 3, 5, 7, 8, 9])

In [38]:
# Find the 0'th index of the latest array you created
arr_random[0]

array([2, 5, 8, 9, 9, 1, 9])

In [39]:
# Get the first 2 rows of latest array you created
arr_random[0:2]

array([[2, 5, 8, 9, 9, 1, 9],
       [7, 9, 8, 1, 8, 8, 3]])

In [51]:
# Get the first 2 values of the first 2 rows of the latest array
arr_random[:3, -1:]

array([[9],
       [3],
       [7]])

In [4]:
import numpy as np
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
randints = np.random.randint(0, 10, size=(3,5))
ones = np.ones((3, 5))
randints, ones

(array([[6, 4, 0, 4, 8],
        [7, 3, 9, 9, 9],
        [0, 5, 2, 6, 8]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [5]:
# Add the two arrays together
a_sum = randints + ones
a_sum

array([[ 7.,  5.,  1.,  5.,  9.],
       [ 8.,  4., 10., 10., 10.],
       [ 1.,  6.,  3.,  7.,  9.]])

In [6]:
import numpy as np
# Create another array of ones of shape (5, 3)
other_ones = np.ones((5,3))
other_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
# Try add the array of ones and the other most recent array together
new_sum = other_ones + a_sum
new_sum

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?
A: The shapes are not similar

How would you fix it?
A: Reshape one.  Most probably the other_ones array.

In [10]:
other_ones = other_ones.reshape(3,5)
other_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
# Now, try calculating new_sum again
new_sum = other_ones + a_sum
new_sum 

array([[ 8.,  6.,  2.,  6., 10.],
       [ 9.,  5., 11., 11., 11.],
       [ 2.,  7.,  4.,  8., 10.]])

In [13]:
# Create another array of ones of shape (3, 5)
other_ones = np.ones((3,5))
other_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
# Subtract the new array of ones from the other most recent array
difference = new_sum - other_ones
difference

array([[ 7.,  5.,  1.,  5.,  9.],
       [ 8.,  4., 10., 10., 10.],
       [ 1.,  6.,  3.,  7.,  9.]])

In [15]:
# Multiply the ones array with the latest array
product = difference * other_ones
product

array([[ 7.,  5.,  1.,  5.,  9.],
       [ 8.,  4., 10., 10., 10.],
       [ 1.,  6.,  3.,  7.,  9.]])

In [16]:
# Take the latest array to the power of 2 using '**'
product_squared = product ** 2
product_squared

array([[ 49.,  25.,   1.,  25.,  81.],
       [ 64.,  16., 100., 100., 100.],
       [  1.,  36.,   9.,  49.,  81.]])

In [17]:
# Do the same thing with np.square()
new_product = np.square(product)
new_product

array([[ 49.,  25.,   1.,  25.,  81.],
       [ 64.,  16., 100., 100., 100.],
       [  1.,  36.,   9.,  49.,  81.]])

In [18]:
# Find the mean of the latest array using np.mean()
mean = np.mean(new_product)
mean

49.13333333333333

In [19]:
# Find the maximum of the latest array using np.max()
max = np.max(new_product)
max

100.0

In [20]:
# Find the minimum of the latest array using np.min()
min = np.min(new_product)
min

1.0

In [21]:
# Find the standard deviation of the latest array
stddev = np.std(new_product)
stddev

35.30225047909678

In [22]:
# Find the variance of the latest array
v = np.var(new_product)
v

1246.2488888888888

In [23]:
# Reshape the latest array to (3, 5, 1)
reshaped = new_product.reshape((3,5,1))
reshaped

array([[[ 49.],
        [ 25.],
        [  1.],
        [ 25.],
        [ 81.]],

       [[ 64.],
        [ 16.],
        [100.],
        [100.],
        [100.]],

       [[  1.],
        [ 36.],
        [  9.],
        [ 49.],
        [ 81.]]])

In [24]:
# Transpose the latest array
reshaped.T

array([[[ 49.,  64.,   1.],
        [ 25.,  16.,  36.],
        [  1., 100.,   9.],
        [ 25., 100.,  49.],
        [ 81., 100.,  81.]]])

What does the transpose do?

In [29]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
a33 = np.random.randint(10, size=(3,3))
a32 = np.random.randint(10, size=(3,2))
a33, a32

(array([[4, 8, 0],
        [6, 6, 9],
        [4, 4, 7]]),
 array([[0, 7],
        [9, 0],
        [2, 3]]))

In [30]:
# Perform a dot product on the two newest arrays you created
dot_prod = a33.dot(a32)
dot_prod

array([[72, 28],
       [72, 69],
       [50, 49]])

In [31]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
b43 = np.random.randint(10, size=(4,3))
c43 = np.random.randint(10, size=(4,3))
b43, c43

(array([[4, 8, 5],
        [8, 8, 3],
        [9, 6, 4],
        [7, 4, 9]]),
 array([[7, 7, 8],
        [3, 5, 7],
        [2, 5, 0],
        [4, 8, 9]]))

In [32]:
# Perform a dot product on the two newest arrays you created
b43.dot(c43)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [34]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
dot_bc = b43.dot(c43.T)
dot_cb = c43.dot(b43.T)
dot_bc, dot_cb

(array([[124,  87,  48, 125],
        [136,  85,  56, 123],
        [137,  85,  48, 120],
        [149, 104,  34, 141]]),
 array([[124, 136, 137, 149],
        [ 87,  85,  85, 104],
        [ 48,  56,  48,  34],
        [125, 123, 120, 141]]))

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [35]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr_a = np.random.randint(10, size=(3,5))
arr_b = np.random.randint(10, size=(3,5))
arr_a, arr_b

(array([[9, 4, 0, 9, 8],
        [5, 0, 9, 2, 8],
        [1, 3, 1, 1, 6]]),
 array([[0, 9, 7, 0, 7],
        [0, 3, 0, 0, 2],
        [2, 4, 9, 6, 5]]))

In [36]:
# Compare the two arrays with '>'
arr_a > arr_b

array([[ True, False, False,  True,  True],
       [ True, False,  True,  True,  True],
       [False, False, False, False,  True]])

What happens when you compare the arrays with `>`?

- The cell at each coordinate in one array is compared with the cell with the same coordinate on the other array and a boolean value is produced.

In [37]:
# Compare the two arrays with '>='
arr_a >= arr_b

array([[ True, False, False,  True,  True],
       [ True, False,  True,  True,  True],
       [False, False, False, False,  True]])

In [38]:
# Find which elements of the first array are greater than 7
arr_a > 7

array([[ True, False, False,  True,  True],
       [False, False,  True, False,  True],
       [False, False, False, False, False]])

In [39]:
# Which parts of each array are equal? (try using '==')
arr_a == arr_b

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [41]:
arr_a, arr_b

(array([[9, 4, 0, 9, 8],
        [5, 0, 9, 2, 8],
        [1, 3, 1, 1, 6]]),
 array([[0, 9, 7, 0, 7],
        [0, 3, 0, 0, 2],
        [2, 4, 9, 6, 5]]))

In [45]:
# Sort one of the arrays you just created in ascending order
sorted_a = np.sort(arr_a, axis=0)
sorted_b = np.sort(arr_b)
sorted_a, sorted_b

(array([[1, 0, 0, 1, 6],
        [5, 3, 1, 2, 8],
        [9, 4, 9, 9, 8]]),
 array([[0, 0, 7, 7, 9],
        [0, 0, 0, 2, 3],
        [2, 4, 5, 6, 9]]))

In [46]:
arr_a

array([[9, 4, 0, 9, 8],
       [5, 0, 9, 2, 8],
       [1, 3, 1, 1, 6]])

In [47]:
# Sort the indexes of one of the arrays you just created
np.argsort(arr_a)

array([[2, 1, 4, 0, 3],
       [1, 3, 0, 4, 2],
       [0, 2, 3, 1, 4]])

In [51]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(arr_a)

0

In [52]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(arr_a)

2

In [54]:
arr_a

array([[9, 4, 0, 9, 8],
       [5, 0, 9, 2, 8],
       [1, 3, 1, 1, 6]])

In [53]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(arr_a, axis=1)

array([0, 2, 4])

In [55]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(arr_a, axis=0)

array([2, 1, 0, 2, 2])

In [57]:
# Create an array of normally distributed random numbers
arr_nd = np.random.randn(3,5)
arr_nd

array([[ 1.35480383,  0.55336387, -0.02506021, -0.10205576, -1.05273498],
       [ 0.01617222, -0.64122577,  0.01230948,  0.50343876, -0.70871586],
       [-1.91002953, -1.05535791,  0.54695531, -1.29392976, -0.2175813 ]])

In [58]:
# Create an array with 10 evenly spaced numbers between 1 and 100
arr1_to_100 = np.linspace(1,100,10)
arr1_to_100

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.